name = "ColorLab"
uuid = "c5b589a2-a6b9-49ee-a8e2-5aea4d514ee8"
authors = ["Li Alex Zhang <fff008@gmail.com>"]
version = "0.2.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
